name: generate_spec_pdf
on:
  push:
    branches:
      - working_draft

jobs:
    # The job that will use the container image you just pushed to ghcr.io
    gen_pdf:
        runs-on: ubuntu-20.04
        container:
            image: pandoc/extra:latest-ubuntu
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Build PDF
              shell: sh
              run: |
                /usr/bin/apt-get -y update
                DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y wkhtmltopdf
                /usr/bin/pip3 install markdownpp
                cd specification
                /usr/local/bin/markdown-pp spec.mdpp -o spec.md
                /usr/bin/sed -i 's|\(<a name=\".*\">\)</a>|\1\&nbsp;</a>|g' spec.md # Work around issue with wkhtmltopdf not linking to empty anchors
                /usr/local/bin/pandoc spec.md -o spec.pdf -f gfm --variable mainfont="DejaVu Sans" --metadata title="FOCUS: FinOps Open Cost and Usage Specification" --pdf-engine=wkhtmltopdf
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v3.1.2
              with:
                # Artifact name
                name: FOCUS_specification
                # A file, directory or wildcard pattern that describes what to upload
                path: specification/spec.pdf
