name: generate_spec_pdf
on:
  push:
    branches:
      - working_draft

jobs:
    # The job that will use the container image you just pushed to ghcr.io
    gen_pdf:
        runs-on: ubuntu-20.04
        container:
            image: pandoc/extra:latest-ubuntu
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install prequirements
              shell: bash
              run: |
                /usr/bin/apt-get -y update
                wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
                DEBIAN_FRONTEND=noninteractive /usr/bin/apt install -y -f ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb
                /usr/bin/pip3 install markdownpp
            - name: Build MD
              shell: bash
              working-directory: ./specification
              run: |
                /usr/local/bin/markdown-pp spec.mdpp -o spec.md
                /usr/bin/sed -i 's|\(<a name=\".*\">\)</a>|\1\&nbsp;</a>|g' spec.md # Work around issue with wkhtmltopdf not linking to empty anchors
            - name: Build PDF
              shell: bash
              working-directory: ./specification
              run: |
                /usr/local/bin/pandoc spec.md -o spec.pdf -f gfm --variable mainfont="DejaVu Sans" --metadata title="FOCUS: FinOps Open Cost and Usage Specification" --pdf-engine=wkhtmltopdf
            - name: Upload Spec PDF
              uses: actions/upload-artifact@v3.1.2
              with:
                # Artifact name
                name: FOCUS_specification
                path: specification/spec.pdf
            - name: Upload Spec MD
              uses: actions/upload-artifact@v3.1.2
              with:
                # Artifact name
                name: FOCUS_specification
                path: specification/spec.md